services:
  # El Mensajero (Broker)
  broker:
    image: eclipse-mosquitto:latest
    container_name: mosquitto_broker
    ports:
      - "1883:1883" # Puerto estándar de MQTT
      - "9001:9001" # Puerto para websockets (visualización)
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - red_industrial
  
  cerebro:
    build: ./brain          # Docker buscará el Dockerfile en esa carpeta
    container_name: cerebro_ia
    depends_on:
      - broker              # No arranca hasta que el broker esté listo
      - db                  # Tampoco arranca hasta que Postgres esté listo
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - red_industrial

  # El Archivero (Base de Datos)
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./db_init/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - red_industrial
  
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana_monitor
    ports:
      - "3000:3000"
    volumes:
      - ./grafana_data:/var/lib/grafana
      - ./grafana_provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - red_industrial

networks:
  red_industrial:
    driver: bridge
